---
title: "json_to_csv"
output: html_document
date: "2023-06-13"
editor_options: 
  chunk_output_type: console
---

## Setup

#Package Setup (if required)

```{r}
#install.packages("jsonlite")
#install.packages("tidyverse")
#install.packages("data.table")
library(jsonlite)
library(tidyverse)
library(data.table)
<<<<<<< HEAD
library(here)
=======
>>>>>>> 08a32b31a643c3c8569db543cd85a405d5037c7f
```

## Initialize

```{r}

<<<<<<< HEAD
# Set the root directory using the here package
root_dir <- here()

#Image Name
input_name = "ubuntu"

directory_path1 = here("02_Preprocessing/02a_jsonTocsv/01_input/Trivy/")
=======
#Image Name
input_name = "ubuntu"

directory_path1 = "/Users/gabecowley/Documents/2023SummerResearch/02_Preprocessing/02a_jsonTocsv/01_input/Trivy/"
>>>>>>> 08a32b31a643c3c8569db543cd85a405d5037c7f

directoryCompletion1 = "Trivy.json"

# Concatenate the directory path and inpute file name
<<<<<<< HEAD
file_path <- here(directory_path1, paste0(input_name, directoryCompletion1))
=======
file_path <- paste0(directory_path1, input_name, directoryCompletion1)
>>>>>>> 08a32b31a643c3c8569db543cd85a405d5037c7f

#Collect Data
json_data <- jsonlite::fromJSON(txt = readLines(file_path))
```

#Pull Desired Values

```{r}
#The problem with this section is that there are several outputs beyond just Vulnerabilities[[1]]. Assuming we want to include all the outputs, we want to write a for-loop to account for it all.
#packageName <- json_data$Results$Vulnerabilities[[1]][[3]]
#vulnerabilityID <- json_data$Results$Vulnerabilities[[1]][[1]]
#severity <- json_data$Results$Vulnerabilities[[1]]$Severity
```

```{r}
# Initialize empty vectors to store the compiled values
packageName <- c()
vulnerabilityID <- c()
severity <- c()

# Check if Vulnerabilities list is empty
if (length(json_data$Results$Vulnerabilities) == 0) {
  # Handle the case when there are no vulnerabilities
  # Set default values or perform any desired actions
  packageName <- NA
  vulnerabilityID <- NA
  severity <- NA
} else {
  # Iterate over each entry in the Vulnerabilities list
  for (entry in json_data$Results$Vulnerabilities) {
    # Extract the values for packageName, vulnerabilityID, and severity from the current entry
    packageName_entry <- entry$PkgName
    vulnerabilityID_entry <- entry$VulnerabilityID
    severity_entry <- entry$Severity

    # Append the values to the respective vectors
    packageName <- c(packageName, packageName_entry)
    vulnerabilityID <- c(vulnerabilityID, vulnerabilityID_entry)
    severity <- c(severity, severity_entry)
  }
}

```

## Create CSV File

#Combine Lists

```{r}
# Combine the lists into a data frame
data <- data.frame(packageName, vulnerabilityID, severity)
```

#Create CSV

```{r}
# Specify the directory path
<<<<<<< HEAD
directory_path2 <- here("02_Preprocessing/02a_jsonTocsv/04_product/Trivy/")

=======
directory_path2 <- "/Users/gabecowley/Documents/2023SummerResearch/02_Preprocessing/02a_jsonTocsv/04_product/Trivy/"

#directoryCompletion2 = "LongTrivy.csv"
>>>>>>> 08a32b31a643c3c8569db543cd85a405d5037c7f
directoryCompletion2 = "Trivy.csv"

# Specify the output file name as a variable
output_name1 <- paste0(input_name, directoryCompletion2)

# Concatenate the directory path and output file name
<<<<<<< HEAD
file_path <- here(directory_path2, output_name1)
=======
file_path <- paste0(directory_path2, output_name1)
>>>>>>> 08a32b31a643c3c8569db543cd85a405d5037c7f

# Save the data frame as a CSV file in the specified directory
write.csv(data, file = file_path, row.names = FALSE)
```
<<<<<<< HEAD
=======

<!-- # Create Wide CSV File -->
<!-- ```{r} -->

<!-- #Create wide CSV -->
<!-- transposed_data <- transpose(data) -->


<!-- # Remove the column names -->
<!-- colnames(transposed_data) <- NULL -->

<!-- # Specify the directory path -->
<!-- directory_path3 <- "/Users/gabecowley/Documents/2023SummerResearch/02_Preprocessing/02a_jsonTocsv/04_product/Trivy/" -->
<!-- directoryCompletion3 <- "WideTrivy.csv" -->

<!-- # Specify the output file name as a variable -->
<!-- output_name2 <- paste0(input_name, directoryCompletion3) -->

<!-- # Specify the output file path -->
<!-- file_path <- paste0(directory_path3, output_name2) -->

<!-- # Save the data frame as a CSV file in the specified directory -->
<!-- write.csv(transposed_data, file = file_path, row.names = FALSE) -->
<!-- ``` -->
>>>>>>> 08a32b31a643c3c8569db543cd85a405d5037c7f
